### ISSUE TITLE
Make hide/show divs expand/contract more gracefully

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#524]
Areas like on the StakePool view to expand and hide "advanced" settings should have smoother/better transitions.  

http://jsfiddle.net/1rnc9bbm/4/
There's an example of a smoother, more pleasing transition in my opinion.

**Comment by Thoughtscript** [comment]
@alexlyp - I'd enjoying doing this one as many other tickets look like there in progress right now.  I'm looking around for a couple more as well.

**Comment by Jascha-Sundaresan** [comment]
Please use react-motion for this.

Here's an example http://chenglou.github.io/react-motion/demos/demo3-todomvc-list-transition/

**Comment by Thoughtscript** [comment]
On it!

**Comment by Thoughtscript** [comment]
@alexlyp - will have proof of concept for you shortly - I have simple React-based reusable component that **doesn't** rely on third-party frameworks (but which can easily incorporate third-party libs should we want react-motion or CXS at any point) and a some simple LESS demo based off the link you shared. I'll post that here in a bit and when you don't have a trillion things going on haha.

**Comment by Thoughtscript** [comment]
@Jascha-Sundaresan - will also build a react-motion example just for fun (I don't think we're using it for anything presently) but to be incorporated if we decide we want to add it!

**Comment by Jascha-Sundaresan** [comment]
coincidentally, it's already a dependency of react-router-transitions which we just merged in today.

**Comment by Thoughtscript** [comment]
Ah fantastic! Thanks!

**Comment by Thoughtscript** [comment]
```
'use strict';

import React from 'react'

const defaultStyle = {
    'background-color': '#33adff',
    'padding': '15px',
    'color': '#fff',
    'opacity': '.6',
    'width': '600px',
    'overflow': 'hidden',
    '-webkit-transition': 'max-height 1.5s cubic-bezier(0, 1.05, 0, 1)',
    '-moz-transition': 'max-height 1.5s cubic-bezier(0, 1.05, 0, 1)',
    'transition': 'max-height 1.5s ease cubic-bezier(0, 1.05, 0, 1)',
    'max-height': '38px',
};

export class ReactHoverDownComponent extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            style: {
                ...defaultStyle,
                ...this.props.customStyle
            },
            ...this.props
        }
    }

    rollDown() {
        this.setState({
            style: {
                ...defaultStyle,
                '-webkit-transition': 'max-height 2s ease',
                '-moz-transition': 'max-height 2s ease',
                'transition': 'max-height 2s ease',
                'max-height': '400px',
                ...this.props.customStyle
            }
        })
    }

    rollUp() {
        this.setState({
            style: {
                ...defaultStyle,
                ...this.props.customStyle
            }
        })
    }

    render() {
        return (
            <div style={this.state.style}
                 ref={el => this.hoverDown = el}
                 onMouseEnter={ el => {this.rollDown() }}
                 onMouseLeave={ el => {this.rollUp() }}>
                {this.props.text || this.props.children}
            </div>
        )
    }
}
```

**Comment by Thoughtscript** [comment]
```javascript
'use strict';

import React from 'react'
import './ScssHoverDownComponent.scss'

export default ({text, children}) => <div className="hover-down">{text || children}</div>
```

**Comment by Thoughtscript** [comment]
```scss
.hover-down {
  background-color: #33adff;
  padding: 15px;
  color: #fff;
  opacity: .5;
  width: 600px;
  overflow: hidden;
  -webkit-transition: max-height 1.5s cubic-bezier(0, 1.05, 0, 1);
  -moz-transition: max-height 1.5s cubic-bezier(0, 1.05, 0, 1);
  transition: max-height 1.5s ease;
  max-height: 38px;
  &:hover {
    -webkit-transition: max-height 2s ease;
    -moz-transition: max-height 2s ease;
    transition: max-height 2s ease;
    max-height: 400px;
  }
}
```
