### ISSUE TITLE
Consolidate uses of <ReactToolTip />

### ISSUE THREAD

**Issue by sndurkin** [decred/decrediton#567]
`<ReactToolTip />` really only needs to be used once within Decrediton, and all elements that have tooltips can share the instance (except for specific instances where an element may want to display tooltips separately from normal ones).

We should add `<ReactToolTip />` to `<App>` (or whatever highest level component makes sense), then use `data-tip` and the other attributes to customize each tooltip on a per-element basis.

**Comment by Thoughtscript** [comment]
This is related to both #570 and potentially #755. The method used to resolve #570 can maybe generalized for all instances?

**Comment by Thoughtscript** [comment]
Current uses of ReactToolTip (as a direct **import**):

1. **components/views/SecurityPage/Page.js** - This is actually an unused ReactToolTip that can be removed completely. I think the intent was to have this here since it's a higher-order component for both **views/SecurityPage/Header.js** as well as **Header/index.js**.

2. **components/views/AccountsPage/AccountRow/Row.js** - "Accounts" from main selection sidebar. Used on Accounts that are not default or imported. This needs getContent...
 
3. **components/views/AccountsPage/AccountRow/index.js** - "Accounts" from main selection sidebar. Used on Accounts that are not default or imported.

4. **components/views/ReceivePage/Page.js** - "Receive" from main selection sidebar. Used in account list dropdown.

5. **components/views/TicketsPage/Page.js** - "Tickets" from main selection sidebar. Used after API Key is loaded in.

6. **components/views/SendPage/Page.js** - "Send" from main selection sidebar. Used only on the wallet/account-tip icon/button.
 
7. **components/views/HomePage/Page.js** - "Overview" from main selection sidebar. Used only on the "Rescan Blockchain" button.

8. **components/views/GetStartedPage/DaemonLoading/Form.j**s - Used when you first start up the app and it's loading the Decred chain. The tip is displayed on the skip sync button that provides an option to skip the sync as a new user.

9. **components/CopyToClipboardButton.js** - Used to show a tooltip on a copy button after something has been copied. The two places where this is used are the **components/views/ReceivePage/Page.js** and **components/SignMessage/index.js**.

**Comment by Thoughtscript** [comment]
Current uses of ReactToolTip (as a direct **import**):

1. **components/views/SecurityPage/Page.js** - This is actually an unused ReactToolTip that can be removed completely. I think the intent was to have this here since it's a higher-order component for both **views/SecurityPage/Header.js** as well as **Header/index.js**.

2. **components/views/AccountsPage/AccountRow/Row.js** - "Accounts" from main selection sidebar. Used on Accounts that are not default or imported. This needs getContent...
 
3. **components/views/AccountsPage/AccountRow/index.js** - "Accounts" from main selection sidebar. Used on Accounts that are not default or imported.

4. **components/views/ReceivePage/Page.js** - "Receive" from main selection sidebar. Used in account list dropdown.

5. **components/views/TicketsPage/Page.js** - "Tickets" from main selection sidebar. Used after API Key is loaded in.

6. **components/views/SendPage/Page.js** - "Send" from main selection sidebar. Used only on the wallet/account-tip icon/button.
 
7. **components/views/HomePage/Page.js** - "Overview" from main selection sidebar. Used only on the "Rescan Blockchain" button.

8. **components/views/GetStartedPage/DaemonLoading/Form.j**s - Used when you first start up the app and it's loading the Decred chain. The tip is displayed on the skip sync button that provides an option to skip the sync as a new user.

9. **components/CopyToClipboardButton.js** - Used to show a tooltip on a copy button after something has been copied. The two places where this is used are the **components/views/ReceivePage/Page.js** and **components/SignMessage/index.js**.

**Comment by Thoughtscript** [comment]
**Changes:**

Top level ReactToolTip placed into **containers/app**

1. **components/views/SecurityPage/Page.js** - Removed. Not needed - e.g. tooltip was loaded with no data since no child element had a data-tip attribute.

2. **components/views/ReceivePage/Page.js** - Removed. The "receive-accounts-button-icon" was not and does not display. Thus, the tooltip here is unneeded. Also tried to resize the button to get it to show. 

3. **components/views/TicketsPage/Page.js** - Removed - tooltip will still render correctly per Issue #755

**Comment by Thoughtscript** [comment]
**Deliberately Unchanged:**

**Comment by Thoughtscript** [comment]
So to **summarize**:

**Three** (3) ReactToolTip DOM instances were completely removed - removing those eliminates unneeded components and rebuilding, **one** (1) was added to the top level, and **four** (4) others currently remain due to specific attributes that must be set on them that cannot (at least not easily or wisely) be set in the top-level component where the top-most ReactToolTip DOM element lives - they were cleaned up however. Advice or suggestions on how to approach them would be welcome.

**Comment by alexlyp** [comment]
@Jascha-Sundaresan is currently removing ReactToolTip in favor of his tooltip built in #807

**Comment by Thoughtscript** [comment]
@alexlyp - I'll jump on replacing all existing instances...

**Comment by Thoughtscript** [comment]
@alexlyp - chatted with @Jascha-Sundaresan - he's already gone through and modified the existing tips. There's one or two left. I'm leaving this to him.

**Comment by Thoughtscript** [comment]
```javascript
'use strict';

import React from 'react'
import './ScssTooltipComponent.scss'

export default ({tip, children, position}) =>
    <div className="tool-tip-wrapper">
        {children}
        <span className={`tool-tip-interior ${position}`}>{tip}</span>
</div>
```

**Comment by Thoughtscript** [comment]
```scss
.tool-tip-wrapper {
  position: relative;
  display: inline-block;
  & > .tool-tip-interior {
    visibility: hidden;
    width: 120px;
    background-color: black;
    color: #fff;
    text-align: center;
    padding: 5px 0;
    border-radius: 6px;
    position: absolute;
    z-index: 1;
    opacity: 0;
    transition: opacity 1s;
  }
  &:hover .tool-tip-interior {
    visibility: visible;
    opacity: .8;
  }
}

.top {
  &.tool-tip-interior {
    width: 120px;
    bottom: 100%;
    left: 50%;
    margin-left: -60px;
    &::after {
      content: " ";
      position: absolute;
      top: 100%;
      left: 50%;
      margin-left: -5px;
      border-width: 5px;
      border-style: solid;
      border-color: black transparent transparent transparent;
    }
  }
}

.right {
  &.tool-tip-interior {
    top: -5px;
    left: 107%;
    &::after {
      content: " ";
      position: absolute;
      top: 50%;
      right: 100%;
      margin-top: -5px;
      border-width: 5px;
      border-style: solid;
      border-color: transparent black transparent transparent;
    }
  }
}

.left {
  &.tool-tip-interior {
    top: -5px;
    right: 107%;
    &::after {
      content: " ";
      position: absolute;
      top: 50%;
      left: 100%;
      margin-top: -5px;
      border-width: 5px;
      border-style: solid;
      border-color: transparent transparent transparent black;
    }
  }
}

.bottom {
  &.tool-tip-interior {
    width: 120px;
    top: 100%;
    left: 50%;
    margin-left: -60px;
    &::after {
      content: " ";
      position: absolute;
      bottom: 100%;
      left: 50%;
      margin-left: -5px;
      border-width: 5px;
      border-style: solid;
      border-color: transparent transparent black transparent;
    }
  }
}
```
